### ISSUE TITLE
output cloudwatch_log_arn returns name not ARN

### ISSUE THREAD

**Issue by yteraoka** [terraform-module/terraform-aws-lambda#10]
## Bug Report

https://github.com/terraform-module/terraform-aws-lambda/blob/c777ccb26d45bd8b85fd8647372036243c6f7076/outputs.tf#L21-L24

output `cloudwatch_logs_arn` returns logGroupName not ARN. 

### Expected Result:

`aws_cloudwatch_log_group.this.arn`

### Actual Result:

`aws_cloudwatch_log_group.this.name`

**Comment by ivankatliarchuk** [comment]
Fixed. Thanks
```
output "cloudwatch_logs_arn" {
  description = "The arn of theh log group."
  value       = aws_cloudwatch_log_group.this.arn
}

output "cloudwatch_logs_name" {
  description = "The name of the log group."
  value       = aws_cloudwatch_log_group.this.name
}
```
