### ISSUE TITLE
what purpose for trigger_transcoder?

### ISSUE THREAD

**Issue by yevgeniyo-ps** [terraform-module/terraform-aws-lambda#7]
## Support Question

Hi, thank you for your module, what purpose of trigger_transcoder IAM policy, why it didnt attach to any object?
https://github.com/terraform-module/terraform-aws-lambda/blob/3bbd86813465220a8c18ca614e7a14af5193deaf/examples/basic/main.tf#L32

Looks like need to add this:

> resource "aws_iam_role_policy_attachment" "lambda-policy-attachment" {
>     role = aws_iam_role.iam.name
>     policy_arn = aws_iam_policy.trigger_transcoder.arn
> }

**Comment by ivankatliarchuk** [comment]
Heh. I should delete this name. I did copy from one of my other projects the policy itself. 
But the policy is required, just name is confusing. Should do the fix soon.
