### ISSUE TITLE
Add support for s3 deployment package

### ISSUE THREAD

**Issue by hammadzz** [terraform-module/terraform-aws-lambda#9]
## Feature Request
Add support for s3_bucket + s3_key parameters of lambda resource instead of just filename.

### Description of Problem:
Wanting to create a lambda with code package from S3 instead of local filesystem.

### Potential Solutions:
I can make a PR on this to contribute. Just wondering was there a reason why this doesn't already exist? It seems straight forward. Maybe there is a HCL limitation?

**Comment by ivankatliarchuk** [comment]
Hi. No there is no limitations. Go for it.
My main case is slightly different. The flow I work with serverless and terraform is.

1.  Deploy infrastructure with terraform. CI with rights to change infrastructure.
2. Ci to manage Lambda lifecycle. e.g. other CI with rights to deploy new code version only

So basically, I do not deploy any code with this module, just placeholder code, if it correct to say. And deploy to s3 pretty much redundant. For sure there is no harm to support multiple deployment options.
